### PR TITLE
Added Rank Functionality

### PR DESCRIPTION
**Pull request by galisufyan-327**
Hi @dstepchew !
I've added the rank on the list view where all the items are displayed, as we discussed before while chatting on Upwork. That rank will be calculated on the basis of votes of item in its list. If we want to show rank on current item show page than we have to calculate cumulative rank of an item from all lists.

Regarding design branch I've merged that in master. You are required to delete master branch from your local system and fetch it again from remote. It will resolve your issues. By moving forward from now you are required to create a new branch from master for your design work and merge it in master after completion of work.

### CODE REVIEW

**Comment by galisufyan-327** [comment]
https://drive.google.com/file/d/16HeMBlHNHVer0DZXsjxlLndCjNEE1Y_p/view?usp=sharing

**Comment by dstepchew** [comment]
Hi @galisufyan-327 - OK I see that you were able to display the rank in the item list, which is great. Are you saying that we would not be able to pull this value into the item show view where there is a list of all the lists an item belongs to? Currently when I visit this link, for instance, I would expect to see "#1" instead of "#0" next to the "Restaurants in Del Mar" list link: http://18.237.91.42/items/board-brew-del-mar

**Comment by galisufyan-327** [comment]
Hi @dstepchew !
No, actually I was saying that, each item can be included inside different lists. How can we calculate rank for item in that case? Do we have to calculate cumulative rank of item in every list and display avg of it on item page? We discussed on this earlier in Upwork chat history. You gave directions to display rank on every item in its own list separately.
So, I'm bit confused on it. Please let me know about it. Thanks!

**Comment by dstepchew** [comment]
Hi @galisufyan-327 I am sorry for the confusion. If an item belongs to list A and it is ranked #1 in that list and also it belongs to list B but it is only ranked #4 on that list, then when you go to the item's view page you would see the lists the item belongs to alongside the current ranking within each list. So in this example if you navigated to the item show view page you would see "This item appears in: List A, rank: #1, List B, rank #4" - Is that not possible? I don't want to display the average. I only want to display the ranking of the item in each list. Let me know if I should mock something up. Thanks!

**Comment by galisufyan-327** [comment]
Hi @dstepchew !
Ah ok. Got it now. Yeah that is simple and I'll do it. Thanks for clearing me!

**Pull request merged**
