### PR TITLE
Ali reward points activities

### PR DESCRIPTION
**Pull request by galisufyan-327**
Functionalities completed in this PR:
1- Added sidekiq for background activities. It will handle reward points and user activities logs in backend.
2- Implemented basic action cable for real time notifications using web-sockets.
3- Archive/Unarchive items if admin or has 5000 points.
4- 11-f: Flagged items or lists should be logged in the same admin queue as above in a different page and accessible to admins and users with 5000 or more points.
5- Corrected seeds.rb file
6- Receive 10 points if an item edit submission is accepted.

Commands for setting this PR:
1- bundle
2- rails db:drop
3- rails db:setup
4- open a new tab in terminal and run sidekiq `bundle exec sidekiq`

### CODE REVIEW

**Comment by galisufyan-327** [comment]
Hi @dstepchew ,

This is a lengthy pr and have many settings/configurations included. Please let me know if you face any issue.

Thanks!
Ali

**Comment by dstepchew** [comment]
Hi @galisufyan-327 - everything is fine (also did db:migrate) except I received error booting sidekiq
2018-06-09T17:31:24.465Z 24748 TID-oxmtft9jk INFO: Booting Sidekiq 5.1.3 with redis options {:id=>"Sidekiq-server-PID-24748", :url=>nil}
Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)

**Comment by galisufyan-327** [comment]
Hi Daniel!
Please confirm that your redis-server is running. To run redis please run this command in a new tab on terminal: "redis-server"

**Comment by galisufyan-327** [comment]
Hi @dstepchew!
Did you figured out the way to fix sidekiq error? Please let me know if required. Thanks.

**Comment by dstepchew** [comment]
Thanks @galisufyan-327 I was able to get it running - I had to install redis first and once I got that running Sidekiq worked fine. I'm now seeing, however, this error when attempting to run rails db:seed : Searchkick::ImportError: {"type"=>"cluster_block_exception", "reason"=>"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"} on item with id '1'
/Users/stepchew/Documents/Sites/bestlist/bestlist/db/seeds.rb:58:in `<top (required)>'
/Users/stepchew/Documents/Sites/bestlist/bestlist/bin/rails:9:in `require'
/Users/stepchew/Documents/Sites/bestlist/bestlist/bin/rails:9:in `<top (required)>'
/Users/stepchew/Documents/Sites/bestlist/bestlist/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:seed

I then tried to create a list manually and received this error: {"type"=>"cluster_block_exception", "reason"=>"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"} on item with id '2'

Thanks,
Dan

**Comment by dstepchew** [comment]
Hi @galisufyan-327 - Results of testing on this last PR:

1. When logged out - attempting to vote on a list item or add a list item/add a list does not force users to login as expected.

2.  I added an item to a list and then archived it. Then logged in as a new user and searched for the item by name and found it (archiving should hide items from all searches). I was also able to reach the item view by typing in the item's original URL - archiving an item should redirect users to a 404 page.

Thanks!
Dan

**Pull request merged**
